### ISSUE TITLE
Fix images in index

### ISSUE THREAD

**Issue by rngkll** [Carbon-Offset-Open-Platform/mainPublicDoc#15]
The text is referring to image-8.png and image-9.png, those files are not present in the repo, image-7 is the highest number available.

It is a good practice to give a descriptive name to the files, without using spaces in the name, we can use camel case or _ instead of space in the name.

line 95: `![alt text](image-8.png)`

line 103: `![alt text](./index/image-9.png)`

**Comment by egcastroleon** [comment]
Renamed the figures from generic numbering to names related to content.  Changed the references to the figures in index.md to reflect the new names.
